# requests.rest為模擬的瀏覽器(須搭配rest client延伸模組)


GET http://localhost/test/a0802-08-query-string.php?a=5&b=10


### 分隔
GET http://localhost/test/a0802-14-for.php

### 分隔
POST http://localhost/test/a0804-02-post-data.php
Content-Type: application/x-www-form-urlencoded

a=100&b=66
#不可隨意空行，要遵循http格式: 方法 -> url
# Content-Type: 告訴server目前資料的格式
#資料都是文字(非檔案上傳)，用urlencoded就可以了
# Content-Type 後面接http的body，中間須空一行


### 分隔
POST http://localhost/test/a0804-02B-post-data.php
Content-Type: application/x-www-form-urlencoded

a=100&b=66